"""No box when unsure: is the difference map's box the size of the part asked for?

Task U2h wires **M1** of the L1 localisation experiment
(``experiments/l1_localise/REPORT.md``, sections 4 and 8).  The difference map
arms its strongest unexplained blob as SAM's box prompt, and on the scanner
that box is wrong more often than it is right for small parts: on D13/scan 37
it was a 6,332-pixel box on a black cable while the part to add back was a
screw of about 300.  A box of the wrong size is worse than none -- sent with
the click, it asks SAM for the cable -- so when the blob's area is outside the
area band of **every** class the frame asks to add back by more than a factor
``k``, the box is withheld and the annotator clicks the part instead.

Where it is on, ``k`` and the bands are configuration:

* ``configs/prompt_gate.yaml`` -- the views (``scan`` only: L1 withheld 36 %
  of the *good* boxes on oak2) and ``k`` (3);
* ``configs/prompt_box_bands.yaml`` -- per view and class, the 5th-95th
  percentile of the areas of the class's *parts* in image pixels (each part
  the median of its old Label Studio drafts), generated by
  ``experiments/l1_localise/fit_bands.py``.

A class without a band (fewer than five parts, or parts from one desktop)
never withholds, and a frame whose card asks for nothing to be added is never
gated.  Nothing here raises: a missing or broken file is a gate that is off,
the box is armed as before, and the log says why (:func:`load_prompt_gate`).

``TDA_PROMPT_GATE`` names another gate file, or ``off``: the test suite sets
it (``tests/conftest.py``), because its synthetic 64 x 64 scan scene has
parts of no real size, and the tests that are about the gate load the
shipped file themselves.
"""
from __future__ import annotations

import logging
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional

__all__ = ["DEFAULT_FILE", "DEFAULT_K", "ENV_VAR", "GateFileError", "PromptGate",
           "Withheld", "load_prompt_gate", "outside_factor"]

log = logging.getLogger(__name__)

DEFAULT_FILE = Path(__file__).resolve().parents[2] / "configs" / "prompt_gate.yaml"
#: Another gate file for this process, or ``off``.
ENV_VAR = "TDA_PROMPT_GATE"
#: L1's factor: the box goes when its area is more than three times above the
#: band's top or below its bottom.
DEFAULT_K = 3.0

Band = tuple[float, float]


def outside_factor(area: float, band: Optional[Band]) -> float:
    """How far outside ``band`` ``area`` is, as a factor >= 1 (1 = inside).

    L1's ``methods.outside_factor``: ``lo / area`` below the band, ``area / hi``
    above it.  No band, or no area, is "inside".
    """
    if band is None or not area or area <= 0:
        return 1.0
    lo, hi = band
    if area < lo:
        return float(lo) / float(area)
    if area > hi:
        return float(area) / float(hi)
    return 1.0


@dataclass(frozen=True)
class Withheld:
    """Why a box was withheld: its area, the classes, how far outside the nearest band."""

    area: int
    classes: tuple[str, ...]
    factor: float


class PromptGate:
    """The views the gate is on for, its factor and its bands."""

    def __init__(self, views: Iterable[str] = (), k: float = DEFAULT_K,
                 bands: Optional[dict] = None) -> None:
        self.views = frozenset(str(v) for v in views)
        self.k = float(k)
        #: ``{view: {cls: (lo_px, hi_px)}}``
        self.bands: dict[str, dict[str, Band]] = {
            str(view): {str(cls): (float(lo), float(hi))
                        for cls, (lo, hi) in (classes or {}).items()}
            for view, classes in (bands or {}).items()
        }

    def applies(self, view: Optional[str]) -> bool:
        """Is the gate on for ``view``?"""
        return str(view) in self.views

    def band(self, view: str, cls: str) -> Optional[Band]:
        """``(lo_px, hi_px)`` of a class in a view, or ``None`` when it has none."""
        return self.bands.get(str(view), {}).get(str(cls))

    def judge(self, view: Optional[str], classes: Iterable[str],
              area: float) -> Optional[Withheld]:
        """``None`` keeps the box; a :class:`Withheld` says why it goes.

        The box is kept when the gate is off for the view, when no class is
        asked for, when any asked-for class has no band (it could be that
        part), and when the area fits any class's band within ``k``.
        """
        if not self.applies(view):
            return None
        asked = tuple(dict.fromkeys(str(c) for c in classes if c))
        if not asked:
            return None
        factors = []
        for cls in asked:
            band = self.band(str(view), cls)
            if band is None:
                return None
            factor = outside_factor(area, band)
            if factor <= self.k:
                return None
            factors.append(factor)
        return Withheld(int(area), asked, min(factors))


class GateFileError(ValueError):
    """Why a gate or bands file cannot be used; the sentence the WARNING says."""


def _read_yaml(path: Path, what: str) -> dict:
    import yaml

    if not path.is_file():
        raise GateFileError(f"the {what} {path} does not exist")
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
    except (OSError, UnicodeDecodeError, yaml.YAMLError) as exc:
        raise GateFileError(f"the {what} {path} cannot be read: "
                            f"{type(exc).__name__}: {exc}") from exc
    if not isinstance(data, dict):
        raise GateFileError(f"the {what} {path} is not a mapping of keys")
    return data


def _parse_k(raw: object) -> float:
    """``k`` as a factor: a finite number of at least 1.

    Below 1 the "band" would be narrower than the band itself -- ``k = 0``
    withholds every box, a negative one too -- so it is not a setting but a
    mistake, and it is treated like any other broken file.
    """
    try:
        k = float(raw)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        raise GateFileError(f"k = {raw!r} is not a number") from None
    if not math.isfinite(k) or k < 1.0:
        raise GateFileError(f"k = {raw!r} is invalid: it is a factor and must be >= 1")
    return k


def _load(target: Path) -> tuple[PromptGate, Path]:
    """The gate a policy file describes, or :class:`GateFileError` saying why not."""
    policy = _read_yaml(target, "gate file")
    raw_views = policy.get("views")
    if not isinstance(raw_views, list) or not all(isinstance(v, str) for v in raw_views):
        raise GateFileError(f"the gate file {target} has no list of views "
                            f"(views: {raw_views!r})")
    k = _parse_k(policy.get("k", DEFAULT_K))
    bands_file = target.parent / str(policy.get("bands") or "prompt_box_bands.yaml")
    fitted = _read_yaml(bands_file, "bands file").get("views")
    if not isinstance(fitted, dict):
        raise GateFileError(f"the bands file {bands_file} has no views")
    bands: dict = {}
    try:
        for view, entry in fitted.items():
            classes = (entry or {}).get("classes") or {}
            bands[str(view)] = {str(cls): (float(row["lo_px"]), float(row["hi_px"]))
                                for cls, row in classes.items()}
    except (AttributeError, KeyError, TypeError, ValueError) as exc:
        raise GateFileError(f"the bands file {bands_file} has a malformed band: "
                            f"{type(exc).__name__}: {exc}") from None
    return PromptGate(raw_views, k, bands), bands_file


def load_prompt_gate(path: Optional[str] = None) -> PromptGate:
    """The gate of ``configs/prompt_gate.yaml`` (or ``path``); never raises.

    Without ``path`` the environment's :data:`ENV_VAR` is read first: ``off``
    is a gate that is off, anything else a file to read instead.

    **Never silently** (task U2i).  A gate that loads says so in one INFO line
    -- the views, ``k``, how many classes have a band and both files -- and
    one that cannot be used says why in a WARNING and is off: a missing or
    malformed gate file, a missing or malformed bands file, a ``k`` that is
    not a number of at least 1.  Off is exactly the box the annotator had
    before, and a typo in a tuning file must not stop anybody annotating; but
    nobody should have to guess, from boxes that keep appearing, that the
    gate never ran.  A view the gate is on for without a single band is a
    WARNING too: the gate would withhold nothing there.
    """
    if path is None:
        chosen = os.environ.get(ENV_VAR, "").strip()
        if chosen.lower() == "off":
            log.info("prompt gate off: %s=off", ENV_VAR)
            return PromptGate()
        path = chosen or None
    target = Path(path) if path else DEFAULT_FILE
    try:
        gate, bands_file = _load(target)
    except Exception as exc:  # noqa: BLE001 - see the docstring
        log.warning("prompt gate OFF, every difference-map box is armed as before: %s",
                    exc)
        return PromptGate()
    banded = {view: len(gate.bands.get(view, {})) for view in sorted(gate.views)}
    log.info("prompt gate on for %s, k=%g, banded classes %s; gate file %s, bands file %s",
             sorted(gate.views) or "no view", gate.k, banded or {}, target, bands_file)
    for view, count in banded.items():
        if not count:
            log.warning("prompt gate: %s is listed in %s but %s has no band for it, "
                        "so no box is withheld there", view, target, bands_file)
    return gate
