"""The "no box when unsure" gate (task U2h, :mod:`tda.ui.prompt_gate`).

L1's M1 (``experiments/l1_localise/REPORT.md``): withhold the difference map's
rank-1 box when its blob's area is outside the area band of every class the
frame asks to add back by more than ``k``.  The window half is in
``tests/test_app_u2h.py``.
"""
from __future__ import annotations

import pytest
import yaml

from tda.ui import prompt_gate as PG

#: D13/scan, the annotator's report that started L1: on frame 37 the rank-1
#: blob was 6,332 px on a black cable, the part a screw (screw.motherboard.03);
#: on frame 38 it was 121 px on a capacitor next to the screw.
D13_37_CABLE_PX = 6332
D13_38_BLOB_PX = 121


@pytest.fixture(scope="module")
def shipped() -> PG.PromptGate:
    return PG.load_prompt_gate(str(PG.DEFAULT_FILE))


# --------------------------------------------------------------------------- #
# the shipped configuration
# --------------------------------------------------------------------------- #
def test_the_gate_is_on_for_scan_only_with_l1s_factor(shipped):
    assert shipped.views == frozenset({"scan"})
    assert shipped.k == 3.0
    for view in ("oak1", "oak2", "rs"):
        assert not shipped.applies(view)
        assert shipped.bands[view], f"no bands for {view}: it could not be turned on"


def test_the_bands_file_is_generated_in_pixels_and_says_so():
    text = (PG.DEFAULT_FILE.parent / "prompt_box_bands.yaml").read_text("utf-8")
    assert "GENERATED by experiments/l1_localise/fit_bands.py" in text
    doc = yaml.safe_load(text)
    assert doc["unit"] == "image px" and doc["min_samples"] == 5
    for view, entry in doc["views"].items():
        for cls, row in entry["classes"].items():
            assert row["samples"] >= doc["min_samples"], (view, cls)
            assert 0 < row["lo_px"] <= row["median_px"] <= row["hi_px"], (view, cls)
        for cls, n in (entry.get("unbanded") or {}).items():
            assert n < doc["min_samples"] and cls not in entry["classes"]


def test_d13_scan_37s_cable_box_is_withheld_and_38s_blob_is_kept(shipped):
    lo, hi = shipped.band("scan", "screw")
    assert D13_37_CABLE_PX > 3 * hi
    verdict = shipped.judge("scan", ["screw"], D13_37_CABLE_PX)
    assert verdict is not None and verdict.classes == ("screw",)
    assert verdict.factor == pytest.approx(D13_37_CABLE_PX / hi)
    assert shipped.judge("scan", ["screw"], D13_38_BLOB_PX) is None
    # the same box on a view the gate is off for is armed as before
    assert shipped.judge("oak2", ["screw"], D13_37_CABLE_PX) is None


def test_a_class_without_a_band_is_never_gated(shipped):
    assert shipped.band("scan", "cooler_bracket") is None      # 4 drafts
    assert shipped.judge("scan", ["cooler_bracket"], 10 ** 9) is None
    assert shipped.judge("scan", ["screw", "cooler_bracket"], 10 ** 9) is None


# --------------------------------------------------------------------------- #
# the rule
# --------------------------------------------------------------------------- #
def gate() -> PG.PromptGate:
    return PG.PromptGate(["scan"], 3.0, {"scan": {"screw": (100.0, 400.0),
                                                 "psu": (80_000.0, 120_000.0)}})


@pytest.mark.parametrize("area, withheld", [
    (33, True), (33.4, False), (100, False), (400, False),
    (1200, False), (1201, True), (6332, True)])
def test_k_is_a_factor_outside_the_band_either_way(area, withheld):
    assert (gate().judge("scan", ["screw"], area) is not None) is withheld


def test_several_classes_keep_the_box_if_any_band_fits():
    g = gate()
    assert g.judge("scan", ["screw", "psu"], 100_000) is None      # the PSU's
    assert g.judge("scan", ["screw", "psu"], 300) is None          # the screw's
    verdict = g.judge("scan", ["screw", "psu"], 6332)
    assert verdict is not None and verdict.classes == ("screw", "psu")
    # the factor is the nearest band's: 80,000 / 6,332 (12.6) beats 6,332 / 400 (15.8)
    assert verdict.factor == pytest.approx(80_000 / 6332)


def test_nothing_asked_for_or_another_view_keeps_the_box():
    g = gate()
    assert g.judge("scan", [], 6332) is None
    assert g.judge("scan", ["", None], 6332) is None
    assert g.judge("oak1", ["screw"], 6332) is None


def test_outside_factor_is_l1s():
    assert PG.outside_factor(50, (100, 400)) == 2.0
    assert PG.outside_factor(800, (100, 400)) == 2.0
    assert PG.outside_factor(200, (100, 400)) == 1.0
    assert PG.outside_factor(200, None) == 1.0
    assert PG.outside_factor(0, (100, 400)) == 1.0


# --------------------------------------------------------------------------- #
# loading never stops anybody annotating
# --------------------------------------------------------------------------- #
def test_off_by_environment_and_by_a_broken_file(tmp_path, monkeypatch):
    monkeypatch.setenv(PG.ENV_VAR, "off")
    assert PG.load_prompt_gate().views == frozenset()
    broken = tmp_path / "gate.yaml"
    broken.write_text("views: [scan\n", encoding="utf-8")
    assert PG.load_prompt_gate(str(broken)).views == frozenset()
    assert PG.load_prompt_gate(str(tmp_path / "missing.yaml")).views == frozenset()


def test_another_gate_file_by_environment(tmp_path, monkeypatch):
    (tmp_path / "bands.yaml").write_text(yaml.safe_dump({"views": {"oak1": {
        "classes": {"screw": {"lo_px": 10, "hi_px": 20, "median_px": 15,
                              "samples": 9}}}}}), encoding="utf-8")
    policy = tmp_path / "gate.yaml"
    policy.write_text("views: [oak1]\nk: 2\nbands: bands.yaml\n", encoding="utf-8")
    monkeypatch.setenv(PG.ENV_VAR, str(policy))
    g = PG.load_prompt_gate()
    assert g.views == frozenset({"oak1"}) and g.k == 2.0
    assert g.band("oak1", "screw") == (10.0, 20.0)
    assert g.judge("oak1", ["screw"], 41) is not None
    assert g.judge("oak1", ["screw"], 40) is None


def test_the_suite_runs_with_the_gate_off():
    """``tests/conftest.py``: the shared scan scene has parts of no real size."""
    assert PG.load_prompt_gate().views == frozenset()
