"""The "no box when unsure" gate (task U2h, :mod:`tda.ui.prompt_gate`).

L1's M1 (``experiments/l1_localise/REPORT.md``): withhold the difference map's
rank-1 box when its blob's area is outside the area band of every class the
frame asks to add back by more than ``k``.  The window half is in
``tests/test_app_u2h.py``.
"""
from __future__ import annotations

import pytest
import yaml

from tda.ui import prompt_gate as PG

#: D13/scan, the annotator's report that started L1: on frame 37 the rank-1
#: blob was 6,332 px on a black cable, the part a screw (screw.motherboard.03);
#: on frame 38 it was 121 px on a capacitor next to the screw.
D13_37_CABLE_PX = 6332
D13_38_BLOB_PX = 121


@pytest.fixture(scope="module")
def shipped() -> PG.PromptGate:
    return PG.load_prompt_gate(str(PG.DEFAULT_FILE))


# --------------------------------------------------------------------------- #
# the shipped configuration
# --------------------------------------------------------------------------- #
def test_the_gate_is_on_for_scan_only_with_l1s_factor(shipped):
    assert shipped.views == frozenset({"scan"})
    assert shipped.k == 3.0
    for view in ("oak1", "oak2", "rs"):
        assert not shipped.applies(view)
        assert shipped.bands[view], f"no bands for {view}: it could not be turned on"


def test_the_bands_file_is_generated_in_pixels_from_parts_and_says_so():
    text = (PG.DEFAULT_FILE.parent / "prompt_box_bands.yaml").read_text("utf-8")
    assert "GENERATED by experiments/l1_localise/fit_bands.py" in text
    doc = yaml.safe_load(text)
    assert doc["unit"] == "image px"
    assert doc["min_parts"] == 5 and doc["min_desktops"] == 2       # U2i
    for view, entry in doc["views"].items():
        for cls, row in entry["classes"].items():
            assert row["parts"] >= 5 and row["desktops"] >= 2, (view, cls)
            assert row["keyframes"] >= row["parts"], (view, cls)
            assert 0 < row["lo_px"] <= row["median_px"] <= row["hi_px"], (view, cls)
        for cls, counts in (entry.get("unbanded") or {}).items():
            assert counts["parts"] < 5 or counts["desktops"] < 2, (view, cls)
            assert cls not in entry["classes"]


def test_one_long_lived_part_is_not_a_class():
    """U2i: one GPU on one desktop, drawn on 32 steps, used to get 1,359-1,359 px."""
    doc = yaml.safe_load((PG.DEFAULT_FILE.parent / "prompt_box_bands.yaml")
                         .read_text("utf-8"))
    scan = doc["views"]["scan"]
    assert "expansion_card" not in scan["classes"]
    assert scan["unbanded"]["expansion_card"] == {"parts": 1, "desktops": 1}
    assert "cooler_bracket" not in scan["classes"]                 # 3 real brackets
    assert scan["unbanded"]["cooler_bracket"]["parts"] == 3


def test_d13_scan_37s_cable_box_is_withheld_and_38s_blob_is_kept(shipped):
    lo, hi = shipped.band("scan", "screw")
    assert D13_37_CABLE_PX > 3 * hi
    verdict = shipped.judge("scan", ["screw"], D13_37_CABLE_PX)
    assert verdict is not None and verdict.classes == ("screw",)
    assert verdict.factor == pytest.approx(D13_37_CABLE_PX / hi)
    assert shipped.judge("scan", ["screw"], D13_38_BLOB_PX) is None
    # the same box on a view the gate is off for is armed as before
    assert shipped.judge("oak2", ["screw"], D13_37_CABLE_PX) is None


def test_a_class_without_a_band_is_never_gated(shipped):
    assert shipped.band("scan", "cooler_bracket") is None      # 3 parts
    assert shipped.judge("scan", ["cooler_bracket"], 10 ** 9) is None
    assert shipped.judge("scan", ["screw", "cooler_bracket"], 10 ** 9) is None


# --------------------------------------------------------------------------- #
# the rule
# --------------------------------------------------------------------------- #
def gate() -> PG.PromptGate:
    return PG.PromptGate(["scan"], 3.0, {"scan": {"screw": (100.0, 400.0),
                                                 "psu": (80_000.0, 120_000.0)}})


@pytest.mark.parametrize("area, withheld", [
    (33, True), (33.4, False), (100, False), (400, False),
    (1200, False), (1201, True), (6332, True)])
def test_k_is_a_factor_outside_the_band_either_way(area, withheld):
    assert (gate().judge("scan", ["screw"], area) is not None) is withheld


def test_several_classes_keep_the_box_if_any_band_fits():
    g = gate()
    assert g.judge("scan", ["screw", "psu"], 100_000) is None      # the PSU's
    assert g.judge("scan", ["screw", "psu"], 300) is None          # the screw's
    verdict = g.judge("scan", ["screw", "psu"], 6332)
    assert verdict is not None and verdict.classes == ("screw", "psu")
    # the factor is the nearest band's: 80,000 / 6,332 (12.6) beats 6,332 / 400 (15.8)
    assert verdict.factor == pytest.approx(80_000 / 6332)


def test_nothing_asked_for_or_another_view_keeps_the_box():
    g = gate()
    assert g.judge("scan", [], 6332) is None
    assert g.judge("scan", ["", None], 6332) is None
    assert g.judge("oak1", ["screw"], 6332) is None


def test_outside_factor_is_l1s():
    assert PG.outside_factor(50, (100, 400)) == 2.0
    assert PG.outside_factor(800, (100, 400)) == 2.0
    assert PG.outside_factor(200, (100, 400)) == 1.0
    assert PG.outside_factor(200, None) == 1.0
    assert PG.outside_factor(0, (100, 400)) == 1.0


# --------------------------------------------------------------------------- #
# loading never stops anybody annotating -- and never falls back silently (U2i)
# --------------------------------------------------------------------------- #
@pytest.fixture
def gate_log():
    """Every record :mod:`tda.ui.prompt_gate` logs from now on.

    A handler on the module's own logger: the application's ``tda`` logger
    does not propagate to the root, so ``caplog`` would miss them once any
    window of the session has configured it.
    """
    import logging

    records: list = []

    class Keep(logging.Handler):
        def emit(self, record):
            records.append(record)

    logger = logging.getLogger(PG.__name__)
    handler, level = Keep(logging.DEBUG), logger.level
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)
    yield records
    logger.removeHandler(handler)
    logger.setLevel(level)


def warnings_in(records) -> list[str]:
    import logging

    return [r.getMessage() for r in records if r.levelno == logging.WARNING]


def write_gate(tmp_path, policy: str, bands=None):
    if bands is not None:
        (tmp_path / "bands.yaml").write_text(yaml.safe_dump(bands), encoding="utf-8")
    target = tmp_path / "gate.yaml"
    target.write_text(policy, encoding="utf-8")
    return str(target)


BANDS = {"views": {"oak1": {"classes": {"screw": {"lo_px": 10, "hi_px": 20,
                                                  "median_px": 15, "parts": 9}}}}}


def test_the_shipped_gate_with_the_variable_unset(monkeypatch, gate_log):
    """What a window loads when nobody set ``TDA_PROMPT_GATE``: views ['scan'], k 3."""
    import logging

    monkeypatch.delenv(PG.ENV_VAR, raising=False)
    g = PG.load_prompt_gate()
    assert sorted(g.views) == ["scan"] and g.k == 3.0
    assert g.band("scan", "screw") is not None
    assert warnings_in(gate_log) == []
    infos = [r.getMessage() for r in gate_log if r.levelno == logging.INFO]
    assert len(infos) == 1, infos
    line = infos[0]
    assert "['scan']" in line and "k=3" in line and "{'scan': 14}" in line
    assert str(PG.DEFAULT_FILE) in line
    assert str(PG.DEFAULT_FILE.parent / "prompt_box_bands.yaml") in line


def test_off_by_environment_says_so(monkeypatch, gate_log):
    monkeypatch.setenv(PG.ENV_VAR, "off")
    assert PG.load_prompt_gate().views == frozenset()
    assert [r.getMessage() for r in gate_log] == [f"prompt gate off: {PG.ENV_VAR}=off"]


@pytest.mark.parametrize("policy, bands, why", [
    (None, BANDS, "does not exist"),
    ("views: [oak1\n", BANDS, "cannot be read"),
    ("- oak1\n", BANDS, "is not a mapping"),
    ("k: 2\nbands: bands.yaml\n", BANDS, "has no list of views"),
    ("views: oak1\nbands: bands.yaml\n", BANDS, "has no list of views"),
    ("views: [oak1]\nbands: nowhere.yaml\n", BANDS, "nowhere.yaml does not exist"),
    ("views: [oak1]\nbands: bands.yaml\n", {"views": {"oak1": {"classes": {
        "screw": {"lo_px": "ten", "hi_px": 20}}}}}, "malformed band"),
    ("views: [oak1]\nbands: bands.yaml\n", {"fitted_from": "x"}, "has no views"),
], ids=["missing", "unparsable", "not-a-mapping", "no-views", "views-not-a-list",
        "bands-missing", "bands-malformed", "bands-without-views"])
def test_a_file_that_cannot_be_used_is_off_with_a_warning(tmp_path, gate_log,
                                                          policy, bands, why):
    target = (str(tmp_path / "gate.yaml") if policy is None       # never written
              else write_gate(tmp_path, policy, bands))
    g = PG.load_prompt_gate(target)
    assert g.views == frozenset() and g.judge("oak1", ["screw"], 10 ** 9) is None
    said = warnings_in(gate_log)
    assert len(said) == 1 and why in said[0], said
    assert "prompt gate OFF" in said[0]


@pytest.mark.parametrize("k", ["0", "-1", "0.5", "-0.0", "nan", "inf", "abc", "[3]"])
def test_a_k_below_one_or_not_a_number_is_off_with_a_warning(tmp_path, gate_log, k):
    g = PG.load_prompt_gate(write_gate(
        tmp_path, f"views: [oak1]\nk: {k}\nbands: bands.yaml\n", BANDS))
    assert g.views == frozenset()
    said = warnings_in(gate_log)
    assert len(said) == 1 and "k = " in said[0], said


@pytest.mark.parametrize("lo, hi", [(10, 0), (0, 20), (-5, 20), (30, 20), (0, 0),
                                    (".nan", 20), (10, ".inf"), ("-.inf", 20)],
                         ids=["hi-zero", "lo-zero", "lo-negative", "reversed", "both-zero",
                              "lo-nan", "hi-inf", "lo-minus-inf"])
def test_an_impossible_band_is_off_with_a_warning(tmp_path, gate_log, lo, hi):
    """U3 minor (a): ``hi_px: 0`` divided by zero on the status line."""
    body = (f"views:\n  oak1:\n    classes:\n      screw:\n"
            f"        lo_px: {lo}\n        hi_px: {hi}\n")
    (tmp_path / "bands.yaml").write_text(body, encoding="utf-8")
    policy = tmp_path / "gate.yaml"
    policy.write_text("views: [oak1]\nbands: bands.yaml\n", encoding="utf-8")
    g = PG.load_prompt_gate(str(policy))
    assert g.views == frozenset() and g.judge("oak1", ["screw"], 10 ** 9) is None
    said = warnings_in(gate_log)
    assert len(said) == 1 and "impossible band for screw on oak1" in said[0], said
    assert "0 < lo_px <= hi_px" in said[0]


def test_a_band_of_one_area_is_possible(tmp_path, gate_log):
    """``lo_px == hi_px``: U2h's expansion_card on scan was exactly that."""
    g = PG.load_prompt_gate(write_gate(
        tmp_path, "views: [oak1]\nbands: bands.yaml\n",
        {"views": {"oak1": {"classes": {"screw": {"lo_px": 20, "hi_px": 20}}}}}))
    assert g.band("oak1", "screw") == (20.0, 20.0) and warnings_in(gate_log) == []
    assert g.judge("oak1", ["screw"], 61) is not None     # 61/20 > 3: no ZeroDivisionError


def test_k_of_one_is_a_band_with_no_slack(tmp_path, gate_log):
    g = PG.load_prompt_gate(write_gate(
        tmp_path, "views: [oak1]\nk: 1\nbands: bands.yaml\n", BANDS))
    assert g.k == 1.0 and g.views == frozenset({"oak1"})
    assert g.judge("oak1", ["screw"], 21) is not None
    assert g.judge("oak1", ["screw"], 20) is None
    assert warnings_in(gate_log) == []


def test_a_listed_view_without_bands_is_on_but_warned_about(tmp_path, gate_log):
    g = PG.load_prompt_gate(write_gate(
        tmp_path, "views: [oak1, scan]\nbands: bands.yaml\n", BANDS))
    assert g.views == frozenset({"oak1", "scan"}) and g.k == PG.DEFAULT_K
    said = warnings_in(gate_log)
    assert len(said) == 1 and "scan is listed" in said[0], said


def test_another_gate_file_by_environment(tmp_path, monkeypatch, gate_log):
    policy = write_gate(tmp_path, "views: [oak1]\nk: 2\nbands: bands.yaml\n", BANDS)
    monkeypatch.setenv(PG.ENV_VAR, policy)
    g = PG.load_prompt_gate()
    assert g.views == frozenset({"oak1"}) and g.k == 2.0
    assert g.band("oak1", "screw") == (10.0, 20.0)
    assert g.judge("oak1", ["screw"], 41) is not None
    assert g.judge("oak1", ["screw"], 40) is None
    assert warnings_in(gate_log) == [] and policy in gate_log[-1].getMessage()


def test_the_suite_runs_with_the_gate_off():
    """``tests/conftest.py``: the shared scan scene has parts of no real size."""
    assert PG.load_prompt_gate().views == frozenset()


# --------------------------------------------------------------------------- #
# the fit: parts, not keyframes (U2i)
# --------------------------------------------------------------------------- #
def _draft(desktop, key, area, cls="screw", view="scan", step=1):
    return {"desktop": desktop, "view": view, "step": step, "instance": key,
            "cls": cls, "area": area, "box": (0, 0, 1, 1)}


def test_a_part_drawn_on_many_steps_counts_once_at_its_median():
    from experiments.l1_localise import fit_bands as F

    drafts = [_draft(13, "ls:GPU#1", 1359, "expansion_card", step=s) for s in range(32)]
    parts = F.part_values(drafts, "scan", "expansion_card")
    assert parts == [(1359.0, 13, 32)]
    assert F.band_of(parts) is None
    # one part, many keyframes of varying size: its median, once
    wobbly = [_draft(13, "ls:Screw#1", a) for a in (100, 300, 200, 250, 5000)]
    assert F.part_values(wobbly, "scan", "screw") == [(250.0, 13, 5)]


def test_a_band_needs_five_parts_from_two_desktops():
    from experiments.l1_localise import fit_bands as F

    one_desktop = [_draft(13, f"ls:Screw#{i}", 200 + i) for i in range(9)]
    assert F.band_of(F.part_values(one_desktop, "scan", "screw")) is None
    four = [_draft(13, "ls:Screw#1", 200), _draft(13, "ls:Screw#2", 210),
            _draft(24, "ls:Screw#1", 220), _draft(24, "ls:Screw#2", 230)]
    assert F.band_of(F.part_values(four, "scan", "screw")) is None
    five = four + [_draft(33, "ls:Screw#1", 240)]
    band = F.band_of(F.part_values(five, "scan", "screw"))
    assert band["parts"] == 5 and band["desktops"] == 3 and band["keyframes"] == 5
    assert band["lo_px"] == pytest.approx(202.0) and band["hi_px"] == pytest.approx(238.0)
    # leave-one-desktop-out: without D33 it is four parts again
    assert F.band_of(F.part_values(five, "scan", "screw", exclude_desktop=33)) is None
    fitted = F.fit(five + one_desktop[:1], views=("scan",))["scan"]
    assert set(fitted["classes"]) == {"screw"} and fitted["unbanded"] == {}
