"""Reporting layer for the Drive log import: the ``--all`` run and its report.

Kept apart from :mod:`tda.core.logs` so the import rules and the batch report
stay separately readable; ``python -m tda.core.logs --all <dir>`` runs
:func:`main` from here.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Optional

from .logs import CHASSIS_KEY, LogImport, import_log, iter_desktop_csvs, read_desktop_csv
from .taxonomy import load_taxonomy


def _expected_steps(meta_csv: Path) -> dict[int, int]:
    """``desktop_id -> n_logged_steps`` from the export's summary table."""
    if not meta_csv.exists():
        return {}
    with open(meta_csv, newline="", encoding="utf-8-sig") as f:
        return {
            int(row["desktop_id"]): int(row["n_logged_steps"])
            for row in csv.DictReader(f)
            if (row.get("desktop_id") or "").strip() and (row.get("n_logged_steps") or "").strip()
        }


def operation_counts(imports: list[LogImport]) -> tuple[int, int]:
    """``(instances operated in >1 step, instances given the same verb twice)``.

    The implicit chassis and the ``?`` placeholders are excluded: neither is a
    single physical part.  The second number must stay 0 -- it can only mean
    two different parts were merged into one instance.
    """
    multi = repeat = 0
    for li in imports:
        per_key: dict[str, list[str]] = {}
        for action in li.actions:
            if action.target == CHASSIS_KEY or action.target not in li.instances:
                continue
            per_key.setdefault(action.target, []).append(action.verb)
        for verbs in per_key.values():
            multi += len(verbs) > 1
            repeat += len(verbs) - len(set(verbs))
    return multi, repeat


def _number_collisions(imports: list[LogImport]) -> int:
    """Instances that share a class, role and sheet number with an earlier one.

    The annotators restarted their numbering per sub-assembly, so these are
    expected; the count is here to show how many parts would have been merged
    by keying identity on the sheet number.
    """
    total = 0
    for li in imports:
        seen: dict[tuple, int] = {}
        for inst in li.instances.values():
            number = inst.attrs.get("sheet_no")
            if number is None:
                continue
            disc = inst.attrs.get("role") or inst.attrs.get("kind") or ""
            seen[(inst.cls, disc, number)] = seen.get((inst.cls, disc, number), 0) + 1
        total += sum(count - 1 for count in seen.values())
    return total


def _by_class(imports: list[LogImport]) -> str:
    counts: dict[str, int] = {}
    for li in imports:
        for inst in li.instances.values():
            counts[inst.cls] = counts.get(inst.cls, 0) + 1
    ordered = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    return ", ".join(f"{cls} {n}" for cls, n in ordered)


def _report(imports: list[LogImport], expected: dict[int, int], directory: Path) -> str:
    multi, repeat = operation_counts(imports)
    lines = [
        "# Drive log import issues",
        "",
        f"Generated by `python -m tda.core.logs --all {directory.as_posix()}`.",
        "",
        f"- desktops: {len(imports)}",
        f"- steps: {sum(len(li.steps) for li in imports)}",
        f"- actions: {sum(len(li.actions) for li in imports)}",
        f"- instances: {sum(len(li.instances) for li in imports)}",
        f"- issues: {sum(len(li.issues) for li in imports)}",
        f"- instances operated in more than one step: {multi} (each one reported below)",
        f"- instances given the same verb twice: {repeat} (must be 0)",
        f"- instances sharing a class, role and sheet number: {_number_collisions(imports)} "
        f"(kept apart on purpose)",
        f"- instances by class: {_by_class(imports)}",
        "",
        "| desktop | brand | steps | n_logged_steps | match | issues |",
        "|---|---|---|---|---|---|",
    ]
    for li in imports:
        want = expected.get(li.desktop)
        mark = "-" if want is None else ("ok" if want == len(li.steps) else "MISMATCH")
        lines.append(
            f"| D{li.desktop:02d} | {li.meta.get('brand_model_raw', '')} | {len(li.steps)} "
            f"| {'' if want is None else want} | {mark} | {len(li.issues)} |"
        )
    lines.append("")
    for li in imports:
        lines.append(f"## D{li.desktop:02d} - {li.meta.get('brand_model_raw', '')}")
        lines.append("")
        if li.issues:
            lines.extend(f"- {text}" for text in li.issues)
        else:
            lines.append("- no issues")
        lines.append("")
    return "\n".join(lines)


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m tda.core.logs",
        description="import every exported Drive log and write the issue report",
    )
    parser.add_argument("--all", metavar="DIR", required=True, help="directory of exported logs")
    parser.add_argument("--out", metavar="PATH", help="issue report (default DIR/import_issues.md)")
    args = parser.parse_args(argv)

    directory = Path(args.all)
    taxonomy = load_taxonomy()
    expected = _expected_steps(directory / "desktop_meta.csv")
    imports: list[LogImport] = []
    for desktop, path in iter_desktop_csvs(directory):
        rows, meta = read_desktop_csv(path)
        imports.append(import_log(desktop, rows, meta, taxonomy))

    out_path = Path(args.out) if args.out else directory / "import_issues.md"
    out_path.write_text(_report(imports, expected, directory), encoding="utf-8")

    mismatched = [
        (li.desktop, len(li.steps), expected[li.desktop])
        for li in imports
        if li.desktop in expected and expected[li.desktop] != len(li.steps)
    ]
    multi, repeat = operation_counts(imports)
    print(
        f"imported {len(imports)} desktops: "
        f"{sum(len(li.steps) for li in imports)} steps, "
        f"{sum(len(li.actions) for li in imports)} actions, "
        f"{sum(len(li.instances) for li in imports)} instances, "
        f"{sum(len(li.issues) for li in imports)} issues; "
        f"{multi} instances operated twice, {repeat} with a repeated verb"
    )
    for desktop, got, want in mismatched:
        print(f"  step-count mismatch D{desktop:02d}: {got} rows vs n_logged_steps {want}")
    if repeat:
        print(f"  INVARIANT: {repeat} instances received the same verb twice")
    print(f"report: {out_path}")
    # A step-count mismatch or a broken invariant must fail the batch run.
    return 1 if mismatched or repeat else 0
